### ISSUE TITLE
5V supply to the entire circuit

### ISSUE THREAD

**Issue by omarojo** [technobly/SparkCore-NeoPixel#11]
Cant I just use a 5v output power supply to power the SparkCore (into the VIN pin), and use the same 5v power supply to power the NeoPixels ?

**Comment by technobly** [comment]
Yes you can, but you'll also want to level shift the output of the Core/Photon to 5V with some of the mentioned level shifters.  If you power from a single cell LiPo battery on VIN (approx. 3.7 volts), you can typically get away with not level shifting the output.

**Comment by omarojo** [comment]
Sorry I got confused there. Newbie question. My plan is to power the Core with the 5v output pin from the RaspberryPi into the VIN pin of the Core (im told the Core can handle that) and I wil use the same 5v source to power the Neopixel ring (since the Core doesnt have 5v out pins, only 3v3) So i dont understand why would I need to level shift the output of the Core, maybe this is a fundamental question I dont get from electronics.

**Comment by technobly** [comment]
You need to make sure the RasperryPi can handle outputting that much current.  The Core draws about 150mA with Wi-Fi on, and each NeoPixel you light up with a 5V supply can consume 60mA if fully bright and WHITE.

Here's a recommended hook up diagram: 
![](http://i.imgur.com/LGRR4CO.jpg)

Neopixels can work fine powered off of 5V and data input 3.3V, generally I've seen this if you don't have a lot of them. If you are breadboarding, try it first... if you get a lot of glitching on the pixels then you probably need to level shift up to 5V.

That said, their datasheet does suggest a 0.7*VDD data input though:
http://www.adafruit.com/datasheets/WS2812B.pdf

...and because they must be powered at a minimum of 3.5V you shouldn't run them off of 3.3V (but I've run them all the way down to 2.6V and they work so YMMV).  A 4.2 - 3.6V LiPo will work ok, but you have to keep the data input high level above that 0.7*VDD.  So if the LiPo is 4.2 - 3.6V that's 2.94 - 2.52.  That should work just fine with a 3.3V data output from the Core or Photon.

If you run them off of 5.0V (RasPi), you need a minimum of a (5.0V*0.7 = 3.5V) data input... so this would be a perfect reason to level shift up to 5V with a single tri-state buffer such as this one:
NL17SZ125XV5T2G if you making your own design, or this one [SN74HCT125N](http://www.digikey.com/product-detail/en/SN74HCT125N/296-8386-5-ND/3768600 if you are breadboarding.
