### ISSUE TITLE
RGBW support

### ISSUE THREAD

**Issue by brendanmatkin** [technobly/SparkCore-NeoPixel#26]
Hey! 

I'm wondering if you still plan to add RGBW neopixel support? It was being discussed on a particle forum for a bit.. 

I was thinking about taking a stab at it but don't really have the time atm, and won't bother if you're already doing it!  Thanks!

**Comment by asamiller** [comment]
I'd really like RGBW support. I posted a bounty to help someone add it. 

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=33172512)](https://www.bountysource.com/issues/33172512-rgbw-support?utm_source=33172512&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by doubravacek** [comment]
I'd really like RGBW support too.

**Comment by jstockdale** [comment]
I have RGBW working and the test ino runs fine on my Photon. It only requires a few changes to this library. I'll try to put together a full pull request. If anyone wants to add a few more bucks to the bounty pool now would be a good time. ;)

Here's a gist that wants to get it working now and doesn't mind that the code is all hacked up (I removed support for all other leds, and there's probably still bugs in the support code where I hacked the 24 bit to 32 bit color support).

https://gist.github.com/jstockdale/856f8abf41f13141d3566477ea551907

**Comment by jamesarm97** [comment]
I just contributed to the bounty. Can't wait to get this working.

**Comment by jamesarm97** [comment]
Will the Adafruit_NeoPixel::setColor() function be modified or added to support passing R,G,B,W? Right now it looks like you have to use the Color function to built the 32bit color.

**Comment by jstockdale** [comment]
Thanks! Yeah. That should be easy enough. I'm not at all clear why the setColor and setColorScaled code is even in this library – I mean, I understand it handles brightness adjustment but they don't seem to be very useful functions as a whole – but tweaking the code to support white through those pathways is pretty trivial.

I'm working on a ph sensor project right now but as soon as I have some extra time I'll tweak on this and get a pull request up. 👍

**Comment by technobly** [comment]
> I'm not at all clear why the setColor and setColorScaled code is even in this library

##### From the README.md:
* Some functions from the [MessageTorch library](https://github.com/plan44/messagetorch/blob/master/messagetorch.cpp#L58-L134) have been added.

These just make it easier to run Messagetorch examples with this library.

Glad to see progress on this request!  If you submit a PR @jstockdale please be sure to keep the pinHI/pinLO defines the same as before.  I would prefer to keep the defines for low level STM access instead of using the inline pinSetFast/pinResetFast functions.  I trust that the low level will not change, and I'm less than certain about the speed of the inline functions as time goes on.

**Comment by jstockdale** [comment]
See the comments from upstream included in the original post. The existing hi lo pin mappings no longer work. You are preferring raw memory mappings instead of convenience functions on an embedded system why? 

Your comments worry me and if you won't accept pinFastSet/pinFastReset improvements I'm not even going to bother submitting a pull request.

I used to be on the Open Source Team for Facebook and I have no desire to contribute code that improves the reliability of your library if you insist on crazy mem mapping to the control registers for non critical timing pathways. I will happily fork your project instead.

**Comment by jstockdale** [comment]
I'm not sure if you missed my comments elsewhere but the existing pinHI pinLO mappings are broken, at least on the version of Particle hardware/firmware/toolchain that I am using. I verified with a logic analyzer that the signal was staying high in between data transmissions instead of flipping low.

**Comment by technobly** [comment]
Hey gang! PR: https://github.com/technobly/SparkCore-NeoPixel/pull/29 has been merged and released on Particle Build.  This supports the new RGBW pixels. Tested and working on Spark Core and Particle Photon.  

See release info here: https://community.particle.io/t/adafruit-neopixel-library-ported/1143/188?u=bdub
