### ISSUE TITLE
Redbear Duo Platform ID in neopixel library

### ISSUE THREAD

**Issue by peterah** [technobly/SparkCore-NeoPixel#27]
When trying to compile an app using the neopixel library onto a Redbear Duo (similar to Photon with BLE) I get an error regarding platform ID. Could you please look into adding the platform ID for the Redbear Duo to the library:
(PLATFORM_ID == 88)
Thanks

**Comment by technobly** [comment]
@peterah thanks for the request!  This turned out to be much simpler than I thought it would be :)  Implemented in PR: https://github.com/technobly/SparkCore-NeoPixel/pull/30

Support for RedBear Duo is now live in the Build IDE!
https://community.particle.io/t/adafruit-neopixel-library-ported/1143/189

**Comment by emcniece** [comment]
Quick note, the Internet Button repo needs this update as well. Will PR if I find time, not likely soon though.

**Comment by technobly** [comment]
FYI: InternetButton library has this update... For a bit now ;-)
