### ISSUE TITLE
Documentation error: SparkCore *can* output 5v

### ISSUE THREAD

**Issue by seanjsavage** [technobly/SparkCore-NeoPixel#7]
When powered via USB, the Spark Core can output 5v via the VIN pin.  I've got mine powering a NeoPixel strip now, and here's another example online:
http://www.bhoite.com/2014/08/spark-core-neopixel-app/

In "nuances" though, the documentation claims otherwise:
https://github.com/technobly/SparkCore-NeoPixel/blob/master/README.md#nuances

**Comment by disrupsean** [comment]
That's odd, because my Spark Core has been powering and controlling a standard Adafruit 60-pixel 1-meter Neopixel strip just fine.  When you describe a diode getting hot though, that makes me nervous – is that enough to cause damage to the Core or strip, or is it a fire hazard?  I will add the external power as you suggest if so.  Thanks for the diagram, that helps.

QUESTION: the triangle just below the Spark Core on the diagram – what does that represent? Forgive my cluelessness with circuitry. I'm assuming that wire just connects to GND on the Core, does this represent something different?

Thanks

**Comment by technobly** [comment]
Sometimes you can get lucky and your Neopixels will just work, even without a level shifter... but it's always going to work great if you use a level shifter and make sure the power supplied to the pixels is well regulated at 5V.

The diode is rated for 3A but it's not heat sinked to run that high.  You should be ok up to 1A through it, but I'd start to question things with 60 pixels.  60mA x 60 = 3.6A assuming they are all white.  Just keep an eye on it, or wire it up like the above drawing.

The triangle is a common schematic symbol for signal ground.  If it had horizontal lines in the shape of a triangle that could be similarly interpreted as signal ground.  If the lines pointed down like a fork, that's earth ground.  I just drew it like a triangle to be fast about it :)

Hope this answers your questions!  If you have more please ask.

**Comment by seanjsavage** [comment]
Am I reading that right: a 1000 μF (1 mF) capacitor in the diagram?
