### ISSUE TITLE
getPixelColor returning dimmed values

### ISSUE THREAD

**Issue by ukmoose** [technobly/SparkCore-NeoPixel#8]
I've been playing around with the neopixel library and appear to have run into an odd result.

If the brightness is dimmed and I run "strip.getPixelColor(i)"  the color returned appears to be the dimmed value.  Which whilst logical is different from the Adafruit Neopixel Library.

The trouble comes in that if you  re-use the color it is then redimmed (and I struggle to think of any use other than to reuse it!)

So lines such as:

strip.setPixelColor(i,strip.getPixelColor(i-1));

won't work to copy a pixels color to the next pixel.

This is different to how the Adafruit Library works which returns the pre-dimmed value so when it is reapplied the resulting displayed color is correct.

**Comment by technobly** [comment]
Thanks for the note!  I see that the way brightness is achieved is by modifying the pixel data in memory, instead of on the fly as it's being written out.  I suppose that's done that way to ensure the timing stays as fast as possible.  Adafruit's library scales the values back up to the normal color value when getPixelColor() is requested:
https://github.com/adafruit/Adafruit_NeoPixel/blob/master/Adafruit_NeoPixel.cpp

I'll make this change as soon as I can, or if you'd like to submit a PR that would be great.

**Comment by AlanGitMan** [comment]
Also I believe that the when using WS2811 pixel type 

        LEDS.setPixelColor(INDEX, r, g, b);

is actually 
        LEDS.setPixelColor(INDEX, g, r, b);

i.e. if you do

        LEDS.setPixelColor(i, 255, 0, 0);

you get bright red and not bright red.  Anyone else seen that?

**Comment by technobly** [comment]
@ukmoose the getPixelColor() has been implemented, but please note it is lossy.  Copying from one pixel to the next is not advised.  Adafruit's library works the same way.  If you want to copy pixel color from one pixel to the next, I would advise keeping a separate array of color data in RAM.

https://github.com/technobly/SparkCore-NeoPixel/blob/master/firmware/neopixel.cpp#L741-L775
